CREATE TABLE dds.fact_flights (
    fact_id SERIAL PRIMARY KEY,
    flight_id INT NOT NULL, -- Уникальный идентификатор рейса (суррогатный ключ)
    date_id INT NOT NULL, -- Ссылка на измерение дат
    airline_id INT NOT NULL, -- Ссылка на измерение авиакомпаний
    airplane_id INT, -- Ссылка на измерение самолетов
    origin_airport_id INT NOT NULL, -- Ссылка на аэропорт вылета
    dest_airport_id INT NOT NULL, -- Ссылка на аэропорт назначения
    weather_id INT, -- Ссылка на измерение погоды
    dep_delay_minutes INT, -- Задержка в минутах
    cancelled BOOLEAN, -- Отмена рейса
    cancellation_reason VARCHAR(10), -- Причина отмены
    distance INT, -- Расстояние между аэропортами
    flight_count INT DEFAULT 1, -- Количество рейсов
    tech_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tech_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (date_id) REFERENCES dds.dim_date(date_id),
    FOREIGN KEY (airline_id) REFERENCES dds.dim_airline(airline_id),
    FOREIGN KEY (origin_airport_id) REFERENCES dds.dim_airport(airport_id),
    FOREIGN KEY (dest_airport_id) REFERENCES dds.dim_airport(airport_id),
    FOREIGN KEY (weather_id) REFERENCES dds.dim_weather(weather_id)
);

INSERT INTO dds.fact_flights (
    flight_id, date_id, airline_id, airplane_id, origin_airport_id, dest_airport_id, weather_id,
    dep_delay_minutes, cancelled, cancellation_reason, distance, flight_count
)
SELECT DISTINCT
    NULL AS flight_id, -- Autogenerated by SERIAL
    dd.date_id,
    da.airline_id,
    dap.airplane_id,
    do_airport.airport_id AS origin_airport_id,
    dd_airport.airport_id AS dest_airport_id,
    dw.weather_id,
    fs.dep_delay_minutes,
    fs.cancelled,
    fs.cancellation_code AS cancellation_reason,
    fs.distance,
    1 AS flight_count
FROM stg.flight_statistics fs
LEFT JOIN dds.dim_date dd ON fs.flight_date = dd.calendar_date
LEFT JOIN dds.dim_airline da ON fs.reporting_airline = da.airline_name
LEFT JOIN dds.dim_airplane dap ON fs.airline_tail_number = dap.tail_number
LEFT JOIN dds.dim_airport do_airport ON fs.origin_airport = do_airport.airport_code
LEFT JOIN dds.dim_airport dd_airport ON fs.dest_airport = dd_airport.airport_code
LEFT JOIN dds.dim_weather dw ON fs.flight_date = dw.weather_date AND fs.origin_airport = dw.airport_code
ON CONFLICT DO NOTHING;